title: "Srinivas Nomula - Personal Website"
description: "PhD Student at Indian Institute of Science"
baseurl: ""
url: "https://sivasrinivasn.github.io"
theme: minima

# Custom variables
name: "Srinivas Nomula"
designation: "PhD Student"
institution: "Indian Institute of Science"
institution_url: "https://iisc.ac.in/"

# Profile icons appear once their URLs are supplied.
social_links:
  google_scholar: "https://scholar.google.com/citations?user=MnM6VHoAAAAJ&hl=en"
  linkedin: "https://in.linkedin.com/in/srinivas-nomula-748a2316b"

# Collections
collections:
  news:
    output: true

defaults:
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"
