title: "Srinivas Nomula"
description: "PhD Student | Indian Institute of Science"
baseurl: ""
url: "https://sivasrinivasn.github.io"

name: "Srinivas Nomula"
designation: "PhD Student"
institution: "Indian Institute of Science"
institution_url: "https://iisc.ac.in/"

# Simple permalink structure
permalink: /:title/

# Build settings
markdown: kramdown
theme: minima