title: "Srinivas Nomula"
description: "PhD Student | Indian Institute of Science"
baseurl: ""
url: "https://sivasrinivasn.github.io"

name: "Srinivas Nomula"
designation: "PhD Student"
institution: "Indian Institute of Science"
institution_url: "https://iisc.ac.in/"

# Add these lines:
permalink: pretty
plugins:
  - jekyll-sitemap
  
# Navigation - add permalinks here
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      permalink: /:title/

# Explicit header pages
header_pages:
  - projects.md
  - contact.md
  - lectures.md
  - misc.md